@startuml
left to right direction
actor "Estudiante" as Estudiante

rectangle "Sistema de Gestion de Tareas Academicas" {
  usecase "Registrar curso" as UC1
  usecase "Registrar actividad" as UC2
  usecase "Editar actividad" as UC3
  usecase "Cambiar estado" as UC4
  usecase "Filtrar actividades" as UC5
  usecase "Visualizar tablero" as UC6
  usecase "Calcular entropia academica" as UC7
  usecase "Guardar informacion" as UC8
}

Estudiante --> UC1
Estudiante --> UC2
Estudiante --> UC3
Estudiante --> UC4
Estudiante --> UC5
Estudiante --> UC6
Estudiante --> UC7

UC1 ..> UC8 : <<include>>
UC2 ..> UC8 : <<include>>
UC3 ..> UC8 : <<include>>
UC4 ..> UC8 : <<include>>
UC6 ..> UC5 : <<include>>
UC7 ..> UC5 : <<include>>
@enduml
